export {Home} from '../pages/Home'
export {AboutUs} from '../pages/AboutUs'
export {Facilities} from '../pages/Facilities'
export {Gallery} from '../pages/Gallery'
export {ContactUs} from '../pages/ContactUs'
export {ErrorPage} from '../pages/ErrorPage'